### ISSUE TITLE
Why raise NotImplementedError from create_rgb_datasets_imgs.py?

### ISSUE THREAD

**Issue by Leno-B** [lartpang/MINet#17]
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    solver = Solver(arg_config, path_config)
  File "/userhome/MINet/code/utils/solver.py", line 57, in __init__
    mode="train",
  File "/userhome/MINet/code/utils/imgs/create_loader_imgs.py", line 84, in create_loader
    use_bigt=arg_config["use_bigt"],
  File "/userhome/MINet/code/utils/imgs/create_rgb_datasets_imgs.py", line 140, in __init__
    raise NotImplementedError
NotImplementedError

**Comment by lartpang** [comment]
@Leno-B

I guess, the error is raised from these code in the newest commit:

https://github.com/lartpang/MINet/blob/567d2e45114e37bd823fd4ebbc28d4a2bb375f2d/code/utils/dataloader.py#L93-L109

So, you need to make sure that any of these items is `True`:
- `if os.path.isdir(root)`
- `elif os.path.isfile(root):

---

It is suggested to use the newest committed version.

**Comment by Leno-B** [comment]
Thanks, it worked when I used the newest committed version.

**Comment by lartpang** [comment]
@Leno-B OK.
I think your problem has been solved. 
If you have any other questions, you are welcome to create a new issue.
