### ISSUE TITLE
Error trying to test trained model

### ISSUE THREAD

**Issue by Sebastian-Schuchmann** [lartpang/MINet#18]
Hello, 

i want to try out on of your trained models on the ESCCD Dataset. I have been trying to follow your readme as close as possible and tried very carefully to do so exactly as you describe but it still fails and I just can't figure it out.

My Config file looks like this:

```
# -*- coding: utf-8 -*-
import os

__all__ = ["proj_root", "arg_config"]

from collections import OrderedDict

proj_root = os.path.dirname(__file__)
datasets_root = "./Dataset/"

ecssd_path = os.path.join(datasets_root, "ESCCD/")

arg_config = {
    "model": "MINet_Res50",  # 实际使用的模型，需要在`network/__init__.py`中导入
    "info": "",  # 关于本次实验的额外信息说明，这个会附加到本次试验的exp_name的结尾，如果为空，则不会附加内容。
    "use_amp": False,  # 是否使用amp加速训练
    "resume_mode": "test",  # the mode for resume parameters: ['train', 'test', '']
    "use_aux_loss": True,  # 是否使用辅助损失
    "save_pre": True,  # 是否保留最终的预测结果
    "epoch_num": 0,  # 训练周期, 0: directly test model
    "lr": 0.001,  # 微调时缩小100倍
    "xlsx_name": "result.xlsx",  # the name of the record file
    # 数据集设置
    "rgb_data": {
        "tr_data_path": ecssd_path,
        "te_data_list": OrderedDict(
            {
                "ecssd": ecssd_path,
            },
        ),
    },
    # 训练过程中的监控信息
    "tb_update": 50,  # >0 则使用tensorboard
    "print_freq": 50,  # >0, 保存迭代过程中的信息
    # img_prefix, gt_prefix，用在使用索引文件的时候的对应的扩展名
    "prefix": (".jpg", ".png"),
    # if you dont use the multi-scale training, you can set 'size_list': None
    # "size_list": [224, 256, 288, 320, 352],
    "size_list": None,  # 不使用多尺度训练
    "reduction": "mean",  # 损失处理的方式，可选“mean”和“sum”
    # 优化器与学习率衰减
    "optim": "sgd_trick",  # 自定义部分的学习率
    "weight_decay": 5e-4,  # 微调时设置为0.0001
    "momentum": 0.9,
    "nesterov": False,
    "sche_usebatch": False,
    "lr_type": "poly",
    "warmup_epoch": 1,  # depond on the special lr_type, only lr_type has 'warmup', when set it to 1, it means no warmup.
    "lr_decay": 0.9,  # poly
    "use_bigt": True,  # 训练时是否对真值二值化（阈值为0.5）
    "batch_size": 4,  # 要是继续训练, 最好使用相同的batchsize
    "num_workers": 4,  # 不要太大, 不然运行多个程序同时训练的时候, 会造成数据读入速度受影响
    "input_size": 320,
}
```

It seems to successfully load the Data and the model, at least the console output says as much.
But on line 250 in the solver.py:
`tqdm_iter = tqdm(enumerate(loader), total=len(loader), leave=False)`
It fails, we can trace the error further into the dataloader.py, where it throws when trying to return a BackgroundGenerator:

```
class DataLoaderX(DataLoader):
    def __iter__(self):
        return BackgroundGenerator(super(DataLoaderX, self).__iter__())
```

This is the whole Log:
When I start the main.py, the following gets printed: 

```
C:\Users\Seppi\Desktop\MINet-master\code>python main.py
 ==============>> 2021-04-30 17:47:57.367696: Initializing... <<==============
 =========>> Project Root: C:\Users\Seppi\Desktop\MINet-master\code <<=========
 ============>> We will not use `torch.backends.cudnn.benchmark` <<============
 =====================>> Training on: ./Dataset/ESCCD/ <<=====================
 ========>> ./Dataset/ESCCD/ is an image folder, we will test on it. <<========
{'batch_size': 4,
 'epoch_num': 0,
 'info': '',
 'input_size': 320,
 'lr': 0.001,
 'lr_decay': 0.9,
 'lr_type': 'poly',
 'model': 'MINet_Res50',
 'momentum': 0.9,
 'nesterov': False,
 'num_workers': 4,
 'optim': 'sgd_trick',
 'prefix': ('.jpg', '.png'),
 'print_freq': 50,
 'reduction': 'mean',
 'resume_mode': 'test',
 'rgb_data': {'te_data_list': OrderedDict([('ecssd', './Dataset/ESCCD/')]),
              'tr_data_path': './Dataset/ESCCD/'},
 'save_pre': True,
 'sche_usebatch': False,
 'size_list': None,
 'tb_update': 50,
 'use_amp': False,
 'use_aux_loss': True,
 'use_bigt': True,
 'warmup_epoch': 1,
 'weight_decay': 0.0005,
 'xlsx_name': 'result.xlsx'}
 ==>> Loading checkpoint 'C:\Users\Seppi\Desktop\MINet-master\code\output\MINet_Res50_S320_BS4_E0_WE1_AMPn_LR0.001_LTpoly_OTsgdtrick_ALy_BIy_MSn\pth\state_final.pth' <<==
 ==>> Loaded checkpoint 'C:\Users\Seppi\Desktop\MINet-master\code\output\MINet_Res50_S320_BS4_E0_WE1_AMPn_LR0.001_LTpoly_OTsgdtrick_ALy_BIy_MSn\pth\state_final.pth' (only has the model's weight params) <<==
 ================>> Total initialization time：0:00:03.281000 <<================
 ==================>> 2021-04-30 17:48:00.650699: Start... <<==================
 ======================>> Testing with testset: ecssd <<======================
 ======================>> Testing on: ./Dataset/ESCCD/ <<======================
 ========>> ./Dataset/ESCCD/ is an image folder, we will test on it. <<========
 ==============>> 2021-04-30 17:48:01.648697: Initializing... <<==============
 =========>> Project Root: C:\Users\Seppi\Desktop\MINet-master\code <<=========
 ============>> We will not use `torch.backends.cudnn.benchmark` <<============
 =====================>> Training on: ./Dataset/ESCCD/ <<=====================
 ========>> ./Dataset/ESCCD/ is an image folder, we will test on it. <<========
{'batch_size': 4,
 'epoch_num': 0,
 'info': '',
 'input_size': 320,
 'lr': 0.001,
 'lr_decay': 0.9,
 'lr_type': 'poly',
 'model': 'MINet_Res50',
 'momentum': 0.9,
 'nesterov': False,
 'num_workers': 4,
 'optim': 'sgd_trick',
 'prefix': ('.jpg', '.png'),
 'print_freq': 50,
 'reduction': 'mean',
 'resume_mode': 'test',
 'rgb_data': {'te_data_list': OrderedDict([('ecssd', './Dataset/ESCCD/')]),
              'tr_data_path': './Dataset/ESCCD/'},
 'save_pre': True,
 'sche_usebatch': False,
 'size_list': None,
 'tb_update': 50,
 'use_amp': False,
 'use_aux_loss': True,
 'use_bigt': True,
 'warmup_epoch': 1,
 'weight_decay': 0.0005,
 'xlsx_name': 'result.xlsx'}
 ==>> Loading checkpoint 'C:\Users\Seppi\Desktop\MINet-master\code\output\MINet_Res50_S320_BS4_E0_WE1_AMPn_LR0.001_LTpoly_OTsgdtrick_ALy_BIy_MSn\pth\state_final.pth' <<==
 ==>> Loaded checkpoint 'C:\Users\Seppi\Desktop\MINet-master\code\output\MINet_Res50_S320_BS4_E0_WE1_AMPn_LR0.001_LTpoly_OTsgdtrick_ALy_BIy_MSn\pth\state_final.pth' (only has the model's weight params) <<==
 ================>> Total initialization time：0:00:03.193000 <<================
 ==================>> 2021-04-30 17:48:04.844698: Start... <<==================
 ======================>> Testing with testset: ecssd <<======================
 ======================>> Testing on: ./Dataset/ESCCD/ <<======================
 ========>> ./Dataset/ESCCD/ is an image folder, we will test on it. <<========
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Seppi\Desktop\MINet-master\code\main.py", line 36, in <module>
    solver.test()
  File "C:\Users\Seppi\Desktop\MINet-master\code\utils\solver.py", line 229, in test
    results = self._test_process(save_pre=self.save_pre)
  File "C:\Users\Seppi\Desktop\MINet-master\code\utils\solver.py", line 250, in _test_process
    tqdm_iter = tqdm(enumerate(loader), total=len(loader), leave=False)
  File "C:\Users\Seppi\Desktop\MINet-master\code\utils\dataloader.py", line 153, in __iter__
    return BackgroundGenerator(super(DataLoaderX, self).__iter__())
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Seppi\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.


```

I am running Windows 10 with Cuda 10.1, Python 3.8.6 and I believe Torch 1.7.1 or something

**Comment by lartpang** [comment]
@Sebastian-Schuchmann 
I think this is caused by the fact that python's multiprocess implementation has different built-in mechanisms on linux and windows.
Maybe you can try to revert DataLoaderX to the DataLoader provided by pytorch, with no parameter changes.

If you have other questions, keep replying.

**Comment by Sebastian-Schuchmann** [comment]
Yes that fixed it!

**Comment by Phoenix-Yang669** [comment]
Thanks

**Comment by Phoenix-Yang669** [comment]
Thanks!!! Although after I moved the code to the if __name__ == '__main__': statement in inference.py, it didn't works. After I searched the problem, moving class (especially InferImageSet) in inference.py to a new .py file works!
